### ISSUE TITLE
[Error] Notebook: Sentiment Analysis with TensorFlow 2

### ISSUE THREAD

**Issue by gonsoomoon-ml** [aws-samples/amazon-sagemaker-script-mode#8] opened 2020-05-29 14:43 UTC
Environment:
  sagemaker notebook: 
   kernel: conda_tensorflow_p36

When I ran the following code cell, I got an error.

transformer = estimator.transformer(instance_count=1, 
                                    instance_type='ml.c5.xlarge')

transformer.transform(csvtest_s3, content_type='text/csv')
print('Waiting for transform job: ' + transformer.latest_transform_job.job_name)
transformer.wait()

What did I do wrong? 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-2747a4a841c9> in <module>()
      1 transformer = estimator.transformer(instance_count=1, 
----> 2                                     instance_type='ml.c5.xlarge')
      3 
      4 transformer.transform(csvtest_s3, content_type='text/csv')
      5 print('Waiting for transform job: ' + transformer.latest_transform_job.job_name)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/tensorflow/estimator.py in transformer(self, instance_count, instance_type, strategy, assemble_with, output_path, output_kms_key, accept, env, max_concurrent_transforms, max_payload, tags, role, model_server_workers, volume_kms_key, endpoint_type, entry_point, vpc_config_override, enable_network_isolation)
    885             endpoint_type=endpoint_type,
    886             entry_point=entry_point,
--> 887             enable_network_isolation=enable_network_isolation,
    888         )
    889 

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/tensorflow/estimator.py in create_model(self, model_server_workers, role, vpc_config_override, endpoint_type, entry_point, source_dir, dependencies, **kwargs)
    592                 source_dir=source_dir,
    593                 dependencies=dependencies,
--> 594                 **kwargs
    595             )
    596 

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/tensorflow/estimator.py in _create_tfs_model(self, role, vpc_config_override, entry_point, source_dir, dependencies, **kwargs)
    635             dependencies=dependencies,
    636             enable_network_isolation=self.enable_network_isolation(),
--> 637             **kwargs
    638         )
    639 

TypeError: type object got multiple values for keyword argument 'enable_network_isolation'

**Comment by rabowskyb** [comment] 2020-05-30 19:37
Hello, thank you for filing this issue.  It was caused by a breaking change to the SageMaker Python SDK.  I have informed the service team and they are working on updating the SDK in notebook instances and SageMaker Studio.  In the meantime, as a temporary solution please do the following to run the notebook:

1)  !pip install -U --user sagemaker
2)  restart kernel

Then you should be able to run the notebook without problems.

**Comment by gonsoomoon-ml** [comment] 2020-05-31 01:10
Hello rabowskyb.
Your suggestion is working. ^^
Thank you for doing that.

**Comment by rabowskyb** [comment] 2020-06-01 20:13
Good to hear, I am glad it is working.  I will close this issue for now in the expectation that the SageMaker service team will soon update the SageMaker Python SDK version in notebook instances and elsewhere.

**Closed as completed by rabowskyb** 2020-06-01 20:13 UTC
